from Triangle import Triangle
print("------------------------------------------------------------")
a = Triangle() 
print(a)
print(f"Parameter : {a.parimeter()}")
print(f"Right Angle Triangle? : {a.IsRightAngle()}")
print("------------------------------------------------------------")
b = Triangle(2)
print(b)
print(f"Parameter : {b.parimeter()}")
print(f"Right Angle Triangle? : {b.IsRightAngle()}")
print("------------------------------------------------------------")
c = Triangle(3,4)
print(c)
print(f"Parameter : {c.parimeter()}")
print(f"Right Angle Triangle? : {c.IsRightAngle()}")
print("------------------------------------------------------------")
d = Triangle(3,4,5)
print(d)
print(f"Parameter : {d.parimeter()}")
print(f"Right Angle Triangle? : {d.IsRightAngle()}")
print("------------------------------------------------------------")
e = Triangle(d)
print(e)
print(f"Parameter : {e.parimeter()}")
print(f"Right Angle Triangle? : {e.IsRightAngle()}")
print("------------------------------------------------------------")
print(f"No of  Triangles: {a.ObjectCount()}")
      